resources:
  - ../../base

patchesStrategicMerge:
  - patch-image-canary.yaml
  #- patch-image-bluegreen.yaml
  #- patch-service-canary.yaml
  - patch-ingress.yaml
  #- patch-analysis.yaml

#commonLabels:
  #env: dev
