apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: http-success-rate
spec:
  metrics:
    - name: success-rate
      provider:
        prometheus:
          address: http://prometheus-operated.default.svc:9090
          query: |
            (sum(rate(http_requests_total{job="myapp",status=~"2.."}[{{args.request_duration}}]))
             /
             sum(rate(http_requests_total{job="myapp"}[{{args.request_duration}}])) ) * 100
      failureCondition: "result < 95"
      successCondition: "result >= 95"
      interval: 15s
      count: 3