apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: http-success-rate
  namespace: default
spec:
  metrics:
    - name: success-rate
      consecutiveSuccessLimit: 1
      interval: 30s
      failureLimit: 0
      successCondition: "result[0] >= 0"
      provider:
        prometheus:
          address: http://prometheus-operated.monitoring.svc.cluster.local:9090
          query: |
            sum(rate(http_requests_total{job="canary", status!~"5.."}[1m]))
            /
            sum(rate(http_requests_total{job="canary"}[1m]))
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-stable-svc
  namespace: default
spec:
  selector:
    app: myapp
    track: canary
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-canary-svc
  namespace: default
spec:
  selector:
    app: myapp
    track: canary
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: myapp-canary
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      track: canary
  template:
    metadata:
      labels:
        app: myapp
        track: canary
    spec:
      containers:
        - name: myapp
          image: ghcr.io/nusrat-dops/argo-rollouts:latest
          ports:
            - containerPort: 80
  strategy:
    canary:
      canaryService: myapp-canary-svc
      stableService: myapp-stable-svc
      trafficRouting:
        ingress:
          name: myapp-ingress
      steps:
        - setWeight: 20
        - pause: { duration: 30s }
        - analysis:
            templates:
              - templateName: http-success-rate
        - setWeight: 50
        - pause: { duration: 30s }
        - setWeight: 100
