name: Build and Deploy Blue/Green Image

on:
  workflow_dispatch:
    inputs:
      color:
        description: "Deployment color (blue or green)"
        required: true
        default: "blue"

permissions:
  contents: write
  packages: write
  pull-requests: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: nusrat-dops/argo-rollouts
  PATCH_FILE: argocd-argo-rollouts-repo/overlays/dev/patch-image-canary.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.color }}-${{ github.run_number }}
          
      - name: Print image tag
        run: echo "✅ Image pushed as ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.color }}-${{ github.run_number }}"

      - name: Update image tag in patch file
        run: |
          echo "Updating ${{ env.PATCH_FILE }} with new image..."
          sed -i "s|image: .*|image: ${{ env.IMAGE }}|" ${{ env.PATCH_FILE }}
          echo "Updated patch file content:"
          cat ${{ env.PATCH_FILE }}

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ${{ env.PATCH_FILE }}
          git commit -m "ci: update image to ${{ env.IMAGE }}"
          git push origin main
