name: Build and Update Canary Image

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: "Optional image tag (default: git commit SHA)"
        required: false

permissions:
  contents: write
  packages: write
  pull-requests: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} # e.g., ghcr.io/username/argo-rollouts

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Define image tag
        id: vars
        run: |
          if [ -n "${{ github.event.inputs.tag }}" ]; then
            TAG=${{ github.event.inputs.tag }}
          else
            TAG=$(echo $GITHUB_SHA | cut -c1-7)
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$TAG" >> $GITHUB_ENV

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.IMAGE }}

      - name: Update image tag in Kustomize patch
        run: |
          echo "Updating image tag in overlays/dev/patch-image-canary.yaml..."
          sed -i "s|image: .*|image: ${{ env.IMAGE }}|" overlays/dev/patch-image-canary.yaml
          echo "Updated patch file:"
          cat overlays/dev/patch-image-canary.yaml

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add overlays/dev/patch-image-canary.yaml
          git commit -m "ci: update image tag to ${{ env.IMAGE }}"
          git push origin main
